name: mnist-project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly  # Remove this line if you want GPU support
  - numpy
  - matplotlib
  - seaborn
  - pillow